/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-03-02 10:35:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import riot.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("    <meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write("     <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>League of legendsをはじめよう</title>\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#relative {\r\n");
      out.write("\t\t\twidth :1200px;\r\n");
      out.write("\t\t\theight :600px;\r\n");
      out.write("\t\t\tposition :relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.absolute {\r\n");
      out.write("\t\t\tposition :absolute;\r\n");
      out.write("\t\t\twidth :300px;\r\n");
      out.write("\t\t\theight :500px;\r\n");
      out.write("\t\t\toverflow :hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#title_img0 {\ttop :0px; left :0px;}\r\n");
      out.write("\t\t#title_img1 { \ttop :0px; left :310px;}\r\n");
      out.write("\t\t#title_img2 {\ttop :0px; left :620px;}\r\n");
      out.write("\t\t#title_img3 {\ttop :0px; left :930px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t#freetoplaycontainer{\r\n");
      out.write("\t\t\tpadding :30px 0px 30px 0px;\r\n");
      out.write("\t\t\twidth :1200px;\r\n");
      out.write("\t\t\theight :400px;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t.freetoplay{\r\n");
      out.write("\t\t\twidth :120px;\r\n");
      out.write("\t\t\theight :120px;\r\n");
      out.write("\t\t\tfloat :left;\r\n");
      out.write("\t\t\tmargin :0px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.h2{\r\n");
      out.write("\t\t\tfont-size :2em;\r\n");
      out.write("\t\t\twidth :900px;\theight :80px;\r\n");
      out.write("\t\t\tpadding-top :40px;\r\n");
      out.write("\t\t\tpadding-left:20px;\r\n");
      out.write("\t\t\ttext-align :left;\r\n");
      out.write("\t\t\tfloat :left;\r\n");
      out.write("\t\t\tcolor :#FFF;\r\n");
      out.write("\t\t\torder :solid 1px #CCC;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ta:visited{\r\n");
      out.write("\t\t\tcolor :#CCC;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#thread {\r\n");
      out.write("\t\t\ttext-decoration :none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.icon{\r\n");
      out.write("\t\t\twidth :100px; height :100px;  \r\n");
      out.write("\t\t\tborder-radius :40px;\r\n");
      out.write("\t\t\toverflow :hidden;\r\n");
      out.write("\t\t\tfloat :left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</style>\r\n");

	String[] freeToPlay = ChampionApi.getFreeToPlay();
	

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t  <div id=\"header_title\">\r\n");
      out.write("\t\t <div id=\"title_lol\">League of legends</div>\r\n");
      out.write("\t\t <div id=\"title_hazimeyou\">をはじめよう</div>\r\n");
      out.write("\t  </div> <div class=\"clear\"></div>\r\n");
      out.write("\t<div id=\"relative\">\r\n");
      out.write("\t\t<div class=\"absolute\" id=\"title_img0\">\r\n");
      out.write("\t\t\t<img  onerror=\"changeImg(0)\" src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg\" alt=\"title\"  />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"absolute\" id=\"title_img1\">\r\n");
      out.write("\t\t\t<img   onerror=\"changeImg(1)\" src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg\" alt=\"title\"  />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"absolute\" id=\"title_img2\">\r\n");
      out.write("\t\t\t<img  onerror=\"changeImg(2)\" src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg\" alt=\"title\"  />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"absolute\" id=\"title_img3\">\r\n");
      out.write("\t\t\t<img  onerror=\"changeImg(3)\" src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_2.jpg\" alt=\"title\"  />\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t</div> <!--  close header -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"content\">");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Lulu.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\r\n");
      out.write("         <h2 class=\"h2\" >League of legends ってなに？</h2>\r\n");
      out.write("         <div class=\"dd\">\r\n");
      out.write("         \t<p>league of legendsは、プレイヤーがひとりのチャンピョンを操作しながら、5v5で戦う、MOBAです。<br />\r\n");
      out.write("                シンプルな操作ながら、初心者から競技レベルのプレイヤーまで幅広く楽しめるゲームです。<br />\r\n");
      out.write("                選べるチャンピョンは現在123体おり、今もなお増え続けるともに、毎月、ゲームのバランス調整が施されています。<br />\r\n");
      out.write("                日本の運営しか体験したことのない人々にとって衝撃的な運営体制はriotgamesが行っています。\r\n");
      out.write("             </p>\r\n");
      out.write("          </div><div class=\"clear\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Singed.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\t\r\n");
      out.write("\t <h2 class=\"h2\">ゲームからeスポーツへ</h2>\r\n");
      out.write("\t \t<div class=\"dd\"><p>スポーツを人間が考案した施設や技術、ルールに則って営まれる、遊戯・競争・肉体鍛錬の要素を含む身体や頭脳を使った行為として定義するならばleague of legendsのプレイ体験はスポーツです。<br />\r\n");
      out.write("\t\t\t\triotは世界各国(アメリカ、EU,中国、韓国、台湾、ブラジル、トルコ、東南アジア)でサービスを提供しており、各国がそれぞれトップのリーグをもっています。<br />\r\n");
      out.write("\t \t\t トップリーグのチームはメンバーが共同生活を営み、日々、プレイのレベル向上をはかっており、これはオーナー企業、スポンサー支援に支えられています。日産はCurceGamingのスポンサーです。<br />\r\n");
      out.write("\t \t\t アメリカや中国では、大学間のリーグも開催され、まさにeスポーツとして、地位を向上させています。\r\n");
      out.write("\t    </p></div><div class=\"clear\"></div>\r\n");
      out.write("\t    \r\n");
      out.write("\t \r\n");
      out.write("\t    <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Katarina.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div> \r\n");
      out.write("\t <h2 class=\"h2\">あなたのサモナーネイムを調べる</h2> \r\n");
      out.write("\t\t<div class=\"dd\" >\r\n");
      out.write("\t        <form action=\"/HEW/JSP/member/match_history.jsp\" action=\"post\" style=\" display :inline ;\">\r\n");
      out.write("\t        \t<p>\r\n");
      out.write("                  サモナーネイムを入力してください<br />\r\n");
      out.write("                  <input type=\"text\" name=\"summonerName\"/>\r\n");
      out.write("                <input type=\"submit\" />\r\n");
      out.write("                ");

                	String errorMessage = (String)request.getAttribute("errorMessage");
                	if(errorMessage != null){
                		out.println(errorMessage);
                	}
                
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("          \t </form>\r\n");
      out.write("\t\t </div><div class=\"clear\"></div>\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Graves.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t <h2 class=\"h2\">チャンピョン人気投票</h2>\r\n");
      out.write("\t \t<div class=\"dd\"><p>\r\n");
      out.write("\t \t\tあなたのお気に入りのチャンピョンを投票して、ランキングを確認しましょう\r\n");
      out.write("\t\t\t<a href=\"/HEW/JSP/question.jsp\" >人気投票へ</a>\t\r\n");
      out.write("\t \t</p></div><div class=\"clear\"></div>\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t\r\n");
      out.write("\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Yasuo.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\t\r\n");
      out.write("\t <h2 class=\"h2\">新規メンバー登録</h2>\r\n");
      out.write("\t \t<div class=\"dd\"><p>\r\n");
      out.write("\t \tメンバー登録\r\n");
      out.write("\t \t<a href=\"/HEW/JSP/login/register_form.jsp\">メンバー登録へ</a>\r\n");
      out.write("\t \t</p></div><div class=\"clear\"></div>\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t\r\n");
      out.write("\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Jinx.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\t\r\n");
      out.write("\t <a id=\"thread\" href=\"/HEW/JSP/board/threadlist.jsp\"><h2 class=\"h2\">Thread一覧へ</h2></a>\r\n");
      out.write("\t \t<div class=\"dd\"><p>\r\n");
      out.write("\t \t\t\r\n");
      out.write("      \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t</p></div><div class=\"clear\"></div>\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Azir.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t <h2 class=\"h2\">グラフ表示</h2>\t\r\n");
      out.write("\t <div class=\"dd\"><p>\r\n");
      out.write("\t <img src=\"/HEW/images/LineChart.jpeg\" />\r\n");
      out.write("\t </p></div><div class=\"clear\"></div>\r\n");
      out.write("\t \r\n");
      out.write("\t <div class=\"icon\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Thresh.png\" / style=\"float :left;\">\t \r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t <h2 class=\"h2\">今週のFree to play</h2>\r\n");
      out.write("\t <div class=\"dd\" id=\"freetoplaycontainer\">\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[0] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[1] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[2] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[3] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[4] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[5] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[6] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[7] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[8] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t \t<div class=\"freetoplay\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/");
      out.print( freeToPlay[9] );
      out.write(".png \"  /></div>\r\n");
      out.write("\t</div><div class=\"clear\"></div>\r\n");
      out.write("\t \r\n");
      out.write("\t</div><!-- close content -->\r\n");
      out.write("  </div> <!--  close wrapper -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
