/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-02-13 10:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write(" <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>League of legendsをはじめよう</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t  <div id=\"header_title\">\r\n");
      out.write("\t\t <div id=\"title_lol\">League of legends</div>\r\n");
      out.write("\t\t <div id=\"title_hazimeyou\">をはじめよう</div>\r\n");
      out.write("\t  </div> <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<img id=\"title_img1\" onmouseover=\"changeImg(1)\" src=\"/HEW/images/champions/loading/ezreal.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img2\"  onmouseover=\"changeImg(2)\" src=\"/HEW/images/champions/loading/ahri.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img3\"  onmouseover=\"changeImg(3)\" src=\"/HEW/images/champions/loading/alister.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img4\"  onmouseover=\"changeImg(4)\" src=\"/HEW/images/champions/loading/azir.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!--  close header -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t <h2 >League of legends ってなに？</h2>\r\n");
      out.write("         <div class=\"dd\"><p>legue of legendsは、プレイヤーがひとりのチャンピョンを操作しながら、5v5で戦う、MOBAです。<br />\r\n");
      out.write("\t \t\t\tシンプルな操作ながら、初心者から競技レベルのプレイヤーまで幅広く楽しめるゲームです。<br />\r\n");
      out.write("\t \t\t\t選べるチャンピョンは現在123体おり、今もなお増え続けるともに、毎月、ゲームのバランス調整が施されています。<br />\r\n");
      out.write("\t \t\t\t日本の運営しか体験したことのない人々にとって衝撃的な運営体制はriotgamesが行っています。\r\n");
      out.write("\t \t </p></div>\r\n");
      out.write("\t \t \r\n");
      out.write("\t <h2>ゲームからeスポーツへ</h2>\r\n");
      out.write("\t \t<div class=\"dd\"><p>スポーツを人間が考案した施設や技術、ルールに則って営まれる、遊戯・競争・肉体鍛錬の要素を含む身体や頭脳を使った行為として定義するならばleague of legendsのプレイ体験はスポーツです。<br />\r\n");
      out.write("\t\t\t\triotは世界各国(アメリカ、EU,中国、韓国、台湾、ブラジル、トルコ、東南アジア)でサービスを提供しており、各国がそれぞれトップのリーグをもっています。<br />\r\n");
      out.write("\t \t\t トップリーグのチームはメンバーが共同生活を営み、日々、プレイのレベル向上をはかっており、これはオーナー企業、スポンサー支援に支えられています。日産はCurceGamingのスポンサーです。<br />\r\n");
      out.write("\t \t\t アメリカや中国では、大学間のリーグも開催され、まさにeスポーツとして、地位を向上させています。\r\n");
      out.write("\t    </p></div>\r\n");
      out.write("\t    \r\n");
      out.write("\t <h2>あなたにオススメのchampionはこれだ</h2> \r\n");
      out.write("\t    <div class=\"dd\"> <p>123体のチャンピョンの中から、あなたにオススメのチャンピョンをセレクトします。<br />\r\n");
      out.write("\t \t\t是非、質問に答えて、あなたのお気に入りを見つけてください<br />\r\n");
      out.write("\t \t\t<a href=\"/HEW/JSP/recommend_champion.jsp\">オススメチャンピョンをみつける</a>\r\n");
      out.write("\t     </p></div>\r\n");
      out.write("\t     \r\n");
      out.write("\t <h2>あなたのサモナーネイムを調べる</h2> \r\n");
      out.write("\t\t<div class=\"dd\" >\r\n");
      out.write("\t        <form action=\"/HEW/JSP/riot/summonerNameToId.jsp\" action=\"post\" style=\" display :inline ;\">\r\n");
      out.write("\t        \t<p>\r\n");
      out.write("                  サモナーネイムを入力してください<br />\r\n");
      out.write("                  <input type=\"text\" name=\"summonerName\"/>\r\n");
      out.write("                <input type=\"submit\" />\r\n");
      out.write("                ");

                	String errorMessage = (String)request.getAttribute("errorMessage");
                	if(errorMessage != null){
                		out.println(errorMessage);
                	}
                
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("          \t </form>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t \r\n");
      out.write("\t <h2>チャンピョン人気投票</h2>\r\n");
      out.write("\t \t<div class=\"dd\"><p>\r\n");
      out.write("\t \t\tあなたのお気に入りのチャンピョンを投票して、ランキングを確認しましょう\r\n");
      out.write("\t\t\t<a href=\"/HEW/JSP/question.jsp\" >人気投票へ</a>\t\r\n");
      out.write("\t \t</p></div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div><!-- close content -->\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("<p style=\"height:200px; display :none\">\r\n");
      out.write("</p>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div> <!--  close wrapper -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
