/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-02-13 04:40:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class question_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("        <meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write("         <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <title>チャンピョンアンケート</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        \r\n");
      out.write("        \th2 {\r\n");
      out.write("        \t\ttext-align :center;\t\r\n");
      out.write("        \t\tfont-size :3em;\r\n");
      out.write("        \t\tmargin-top :100px;\r\n");
      out.write("        \t\tmargin-bottom :100px;\r\n");
      out.write("        \t\ttext-indent :0em;\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t}\r\n");
      out.write("        \r\n");
      out.write("        \t#content{\r\n");
      out.write("        \t\tpadding-left :50px;\t\r\n");
      out.write("        \t\r\n");
      out.write("        \t}\r\n");
      out.write("             body {\r\n");
      out.write("   \t             color :#FFF;\r\n");
      out.write("             } \r\n");
      out.write("             \r\n");
      out.write("             .champion{\r\n");
      out.write("             \tfloat :left;\r\n");
      out.write("             \toverfloa :auto;\r\n");
      out.write("             \twidth :200px;\r\n");
      out.write("             \tmargin-right :20px;\r\n");
      out.write("             \ttext-align: center;\r\n");
      out.write("             }\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("        </style>\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<h2>あなたのお気に入りを教えてください</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<form action=\"./database/DB_favarite.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"champion\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg\" alt=\"img\" width=\"200\" height=\"400\"  />\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"select\"  value=\"Aatrox\" />Aatrox\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"champion\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg\" alt=\"img\" width=\"200\" height=\"400\"  />\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"select\"  value=\"\" />Aatrox\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"champion\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg\" alt=\"img\" width=\"200\" height=\"400\"  />\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"select\"  value=\"\" />Aatrox\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"champion\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg\" alt=\"img\" width=\"200\" height=\"400\"  />\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"select\"  value=\"\" />Aatrox\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"champion\" >\r\n");
      out.write("\t\t\t\t\t<img src=\"http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg\" alt=\"img\" width=\"200\" height=\"400\"  />\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"select\"  value=\"\" />Aatrox\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t<input type=\"submit\" />\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div><!--  content -->\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div><!--  wrapper -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
