/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-02-12 08:37:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommend_005fchampion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write(" <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>オススメ　チャンピョン</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t  <div id=\"header_title\">\r\n");
      out.write("\t\t <div id=\"title_lol\">League of legends</div>\r\n");
      out.write("\t\t <div id=\"title_hazimeyou\">をはじめよう</div>\r\n");
      out.write("\t  </div> <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<img id=\"title_img1\" onmouseover=\"changeImg(1)\" src=\"/HEW/images/champions/loading/ezreal.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img2\"  onmouseover=\"changeImg(2)\" src=\"/HEW/images/champions/loading/ahri.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img3\"  onmouseover=\"changeImg(3)\" src=\"/HEW/images/champions/loading/alister.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\r\n");
      out.write("\t\t<img id=\"title_img4\"  onmouseover=\"changeImg(4)\" src=\"/HEW/images/champions/loading/azir.jpg\" alt=\"title\" width=\"264\" height=\"480\" />\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!--  close header -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"recommend\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"question\">\r\n");
      out.write("        <p style=\"margin :30px;\">好きなvisualを選んでください</p>\r\n");
      out.write("                <form class=\"form\" action=\"/HEW/JSP/dispatcher/result.jsp\"  method=\"post\">\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"annie\" />女の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"draven\" />男の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"3\" />忍者</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"4\" />メカ</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"submit\" value=\"送信\" />\r\n");
      out.write("                </form>\r\n");
      out.write("         </div> \r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"question\">\r\n");
      out.write("        <p style=\"margin :30px;\">好きな~を選んでください</p>\r\n");
      out.write("                <form class=\"form\" action=\"result.jsp\" method=\"post\">\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"annie\" />女の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"b\" />男の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"c\" />忍者</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"d\" />メカ</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"submit\" value=\"送信\" />\r\n");
      out.write("                </form>\r\n");
      out.write("         </div> \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"question\">\r\n");
      out.write("        <p style=\"margin :30px;\">好きな~を選んでください</p>\r\n");
      out.write("                <form class=\"form\" action=\"result.jsp\" method=\"post\">\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"1\" />女の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"2\" />男の子</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"3\" />忍者</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"radio\" name=\"answer\" value=\"4\" />メカ</p>\r\n");
      out.write("                        <p class=\"radio\"><input type=\"submit\" value=\"送信\" />\r\n");
      out.write("                </form>\r\n");
      out.write("         </div> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div><!--  close recommend -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
