/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-03-03 10:18:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import HEW.*;
import board.*;

public final class threadlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("    <meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write("    <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\t<title>Thread List</title>\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tcolor :#fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#threadlist{\r\n");
      out.write("\t\t\twidth :700px;\r\n");
      out.write("\t\t\tfloat :left;\r\n");
      out.write("\t\t\theight :2000px;\r\n");
      out.write("\t\t\tbackground-color :rgba(255,255,255,0.3);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#threadcreate{\r\n");
      out.write("\t\t\twidth :400px;\r\n");
      out.write("\t\t\theight :2000px;\r\n");
      out.write("\t\t\tfloat :right;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.thread{\r\n");
      out.write("\t\t\tcolor :#FFF;\r\n");
      out.write("\t\t\tfont-size :2em;\r\n");
      out.write("\t\t\twidth :600px;\r\n");
      out.write("\t\t\theight :50px;\r\n");
      out.write("\t\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ta{\r\n");
      out.write("\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ta:link {color :#FFF;\t} a:visited { color :#FFF;}\r\n");
      out.write("\t\ta:hover {color :#aaa;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"threadlist\">\r\n");
      out.write("\t\t");

			board.Thread threadroot = DBinterface.createThreadList();
			threadroot.getThreadList(out);
		
      out.write("\r\n");
      out.write("\t</div>\t<!-- threadlist close -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"threadcreate\">\r\n");
      out.write("        <div class=\"form\">\r\n");
      out.write("                <form id=\"createthread\" action=\"/HEW/ThreadDispatcher\" method=\"post\">\r\n");
      out.write("                        threadのタイトル<input type=\"text\" name=\"threadtitle\"/>\r\n");
      out.write("                        threadの内容<input type=\"text\" name=\"threadcontent\"/>\r\n");
      out.write("                         <input name=\"type\" value=\"thread\"  style=\"display :none;\" />\r\n");
      out.write("                         <input type=\"submit\" value=\"threadの作成\"/>\r\n");
      out.write("                </form>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("</div><!--  close wrapper -->\r\n");
      out.write("<a href=\"http://localhost:8080/HEW/JSP/index.jsp\">\r\n");
      out.write("\t<div id=\"toTOP\"style=\"width :150px; height: 150px;  position :fixed; bottom :20px; right :50px; color :#FFF; opacity :0.2\" onmouseover =\"teemo()\"\t onmouseout=\"killteemo()\">\r\n");
      out.write("\t\t<p style=\"\">TOPへ</p>\r\n");
      out.write("\t\t<div style=\"width :120px; height :120px; overflow :hidden; border-radius :30px;\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Teemo.png\" /></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction teemo(){\r\n");
      out.write("\t\tdocument.getElementById(\"toTOP\").style.opacity =\"1.0\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction killteemo(){\r\n");
      out.write("\t\t document.getElementById(\"toTOP\").style.opacity = \"0.2\";\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
