/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2015-03-03 10:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import HEW.*;
import board.*;

public final class thread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("    <meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write("    <link href=\"/HEW/CSS/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/jquery-1.11.2.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/HEW/JavaScript/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Thread</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tcolor :#fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.level0{\r\n");
      out.write("\t\twidth :1000px;\r\n");
      out.write("\t\tbackground-color :rgba(255,255,255,0.4);\r\n");
      out.write("\t\tborder :solid 1px #ddd;\r\n");
      out.write("\t\tmargin:30px auto;\r\n");
      out.write("\t\tpadding :20px 0px 20px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.level0content{\r\n");
      out.write("\t\tfont-size :1.5em;\r\n");
      out.write("\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.level1{\r\n");
      out.write("\t\twidth :980px;\r\n");
      out.write("\t\tbackground-color :rgba(100,100,100,0.4);\r\n");
      out.write("\t\tpadding :20px 0px 10px 20px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.level2{\r\n");
      out.write("\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t\twidth :960px;\r\n");
      out.write("\t\tbackground-color :rgba(255,255,255,0.4);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.level3{\r\n");
      out.write("\t\twidth :940px;\r\n");
      out.write("\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t\tbackground-color :rgba(100,100,100,0.4);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.level4{\r\n");
      out.write("\t\tbackground-color :rgba(255,255,255,0.4);\r\n");
      out.write("\t\twidth :920px;\r\n");
      out.write("\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.level5{\r\n");
      out.write("\t\tbackground-color :rgba(100,100,100,0.4);\r\n");
      out.write("\t\twidth :900px;\r\n");
      out.write("\t\tpadding :20px 0px 0px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.level6{\r\n");
      out.write("\t\tbackground-color :rgba(100,100,100,0.4);\r\n");
      out.write("\t\twidth :880px;\r\n");
      out.write("\t\tpadding:20px 0px 0px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#submit{\r\n");
      out.write("\t\tmargin :auto;\r\n");
      out.write("\t\twidth :1022px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#textarea{\r\n");
      out.write("\t\tmargin :auto;\r\n");
      out.write("\t\twidth :1022px;\r\n");
      out.write("\t\theight :300px;\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton{\r\n");
      out.write("\t\t border-top: 1px solid #ccc;  \r\n");
      out.write("   \t\t border-right: 1px solid #999;  \r\n");
      out.write("    \tborder-bottom: 1px solid #999;  \r\n");
      out.write("    \tborder-left: 1px solid #ccc;  \r\n");
      out.write("    \tfont-weight: bold;  \r\n");
      out.write("    \tpadding :0px 5px;\r\n");
      out.write("    \tcursor: pointer;  \r\n");
      out.write("    \tcolor: #666;  \r\n");
      out.write("    \topacity :0.5;\r\n");
      out.write("    \tmargin-left :10px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t");

		int threadID = Integer.valueOf(request.getParameter("threadID"));
	
		Message rootmessage = DBinterface.createBoard(threadID);
		rootmessage.getContent(out);
		
		int size = rootmessage.responseList.size();


	
      out.write("\r\n");
      out.write("\t<div class=\"form\" style=\"display:none; \" id=\"form\" >\r\n");
      out.write("\t\t<form  action=\"/HEW/ThreadDispatcher\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"responseTo\" value=\"\"   id=\"responseTo\" style=\"display :none;\" />\r\n");
      out.write("\t\t \t<p id=\"submit\"><input type=\"submit\" value=\"messageの作成\"/></p>\r\n");
      out.write("\t\t\t<p id=\"textarea\"><textarea name=\"content\" rows=\"10\" cols=\"40\"> </textarea></p>\r\n");
      out.write("\t\t \t<input name=\"type\" value=\"message\"  style=\"display :none;\" />\r\n");
      out.write("\t\t \t<input name=\"threadID\" value=\"");
      out.print( threadID );
      out.write("\" style=\"display :none;\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<p><a href=\"/HEW/JSP/board/threadlist.jsp\">一覧にもどる</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t//返信ボタンがおされたときにテキストエリアを表示する。\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"button\").click(function(){\r\n");
      out.write("\t\t\t\tvar responseID = $(this).attr(\"value\")\r\n");
      out.write("\t\t\t\t$(\"#form\").show(\"slow\");\r\n");
      out.write("\t\t\t\t$(\"#responseTo\").attr(\"value\",responseID);\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<a href=\"http://localhost:8080/HEW/JSP/index.jsp\">\r\n");
      out.write("\t<div id=\"toTOP\"style=\"width :150px; height: 150px;  position :fixed; bottom :20px; right :50px; color :#FFF; opacity :0.2\" onmouseover =\"teemo()\"\t onmouseout=\"killteemo()\">\r\n");
      out.write("\t\t<p style=\"\">TOPへ</p>\r\n");
      out.write("\t\t<div style=\"width :120px; height :120px; overflow :hidden; border-radius :30px;\"><img src=\"http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Teemo.png\" /></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction teemo(){\r\n");
      out.write("\t\tdocument.getElementById(\"toTOP\").style.opacity =\"1.0\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction killteemo(){\r\n");
      out.write("\t\t document.getElementById(\"toTOP\").style.opacity = \"0.2\";\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
